env:
  browser: true
  es2021: true
extends:
  - "plugin:react/recommended"
  - google
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - prettier
rules:
  {
    "prettier/prettier":
      [
        "error",
        {
          "printWidth": 80,
          "trailingComma": "es5",
          "semi": false,
          "jsxSingleQuote": true,
          "singleQuote": true,
          "useTabs": true,
        },
      ],
    "require-jsdoc": 0
  }
settings:
  react:
    version: detect