service: custom-message

provider:
  name: aws
  profile: ${opt:aws-profile}
  region: ${opt:region}
  deploymentBucket:
    name: ${env:APP_NAME}-deployment-bucket
  stackName: ${env:APP_NAME}-custom-message

functions:
  customMessage:
    name: ${env:APP_NAME}-custom-message
    runtime: python3.8
    timeout: 300
    handler: custom_message.handler