service: custom-message
variablesResolutionMode: 20210326

plugins:
  - serverless-python-requirements

provider:
  name: aws
  profile: ${opt:aws-profile}
  region: ${opt:region}
  deploymentBucket:
    name: ${env:APP_NAME}-deployment-bucket
  stackName: ${env:APP_NAME}-custom-message
  lambdaHashingVersion: "20201221"

functions:
  customMessage:
    name: ${env:APP_NAME}-custom-message
    runtime: python3.8
    timeout: 300
    handler: custom_message.handler

resources:
  extensions:
    CustomMessageLambdaFunction:
      Properties:
        Environment:
          Variables:
            APP_BASE_URL: ${env:APP_BASE_URL}
            API_BASE_URL: ${env:API_BASE_URL}
  Resources:
    UserPoolCustomMessageLambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:invokeFunction
        Principal: cognito-idp.amazonaws.com
        FunctionName: ${env:APP_NAME}-custom-message
        SourceArn: arn:aws:cognito-idp:${opt:region}:${aws:accountId}:userpool/${env:USER_POOL_ID}