service: custom-message

plugins:
  - serverless-python-requirements

custom:
  functionName: ${env:APP_NAME}-custom-message
  userPoolArn: arn:aws:cognito-idp:${opt:region}:${aws:accountId}:userpool/${env:USER_POOL_ARN}

provider:
  name: aws
  profile: ${opt:aws-profile}
  region: ${opt:region}
  deploymentBucket:
    name: ${env:APP_NAME}-deployment-bucket
  stackName: ${custom:functionName}
  lambdaHashingVersion: "20201221"

functions:
  customMessage:
    name: ${custom:functionName}
    runtime: python3.8
    timeout: 300
    handler: custom_message.handler

resources:
  extensions:
    CustomMessageLambdaFunction:
      Properties:
        Environment:
          Variables:
            APP_BASE_URL: ${env:APP_BASE_URL}
            API_BASE_URL: ${env:API_BASE_URL}
    UserPoolCustomMessageLambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:invokeFunction
        Principal: cognito-idp.amazonaws.com
        FunctionName: ${self:custom:functionName}
        SourceArn: ${self:custom:userPoolArn}