service: amplify-app

provider:
  name: aws
  profile: ${opt:aws-profile}
  region: ${opt:region}
  deploymentBucket:
    name: ${env:APP_NAME}-deployment-bucket
  stackName: ${env:APP_NAME}-amplify-app

resources:
  Resources:
    AmplifyRole:
      Type: AWS::IAM::Role
      DeletionPolicy: Delete
      Properties:
        RoleName: ${env:APP_NAME}-amplify-role
        Description: Amplify app IAM role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - amplify.amazonaws.com
              Action:
                - sts:AssumeRole
    AmplifyApp:
      DependsOn:
        - AmplifyRole
      Type: AWS::Amplify::App
      DeletionPolicy: Delete
      Properties:
        CustomRules: 
          - Source: "/site.webmanifest"
            Status: "200"
            Target: "/site.webmanifest"
          - Source: "/icon.ico"
            Status: "200"
            Target: "/icon.ico"
          - Source: "/icon16x16.png"
            Status: "200"
            Target: "/icon16x16.png"  
          - Source: "/icon32x32.png"
            Status: "200"
            Target: "/icon32x32.png"  
          - Source: "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>"
            Status: "200"
            Target: "/index.html"
          - Source: "/<*>"
            Status: "404"
            Target: "/index.html"
        Description: Amplify app for React app
        EnableBranchAutoDeletion: false
        EnvironmentVariables: 
          - Name: CHOKIDAR_USEPOLLING
            Value: "1"
          - Name: CI
            Value: "1"
          - Name: _LIVE_UPDATES
            Value: '[{"pkg":"@aws-amplify/cli","type":"npm","version":"latest"}]'
        IAMServiceRole: !GetAtt AmplifyRole.Arn
        Name: ${env:APP_NAME}-amplify-app
        OauthToken: ${env:GH_TOKEN}
        Repository: ${env:GH_REPO}
    AmplifyRolePolicy:
      DependsOn:
        - AmplifyRole
        - AmplifyApp
      Type: 'AWS::IAM::Policy'
      Properties:
        PolicyName: ${env:APP_NAME}-amplify-app
        Roles:
          - !Ref AmplifyRole
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - amplify:*
              Resource: !GetAtt AmplifyApp.Arn
    AmplifyBranch:
      Type: AWS::Amplify::Branch
      Properties: 
        AppId: !GetAtt AmplifyApp.AppId
        BranchName: ${env:GH_BRANCH}
        Description: Deployment branch for Amplify app
        EnableAutoBuild: true
        EnablePerformanceMode: false
        EnablePullRequestPreview: false
        EnvironmentVariables: 
          - Name: USER_BRANCH
            Value: ${env:GH_BRANCH}
          - Name: REACT_APP_LOCAL
            Value: 'false'
          - Name: REACT_APP_DEBUG
            Value: 'false'
          - Name: REACT_APP_IDENTITY_POOL_ID
            Value: ${env:IDENTITY_POOL_ID}
          - Name: REACT_APP_AWS_REGION
            Value: ${opt:region}
          - Name: REACT_APP_USER_POOL_ID
            Value: ${env:USER_POOL_ID}
          - Name: REACT_APP_USER_POOL_CLIENT
            Value: ${env:USER_POOL_CLIENT}
          - Name: REACT_APP_API_URL
            Value: ${env:API_URL}
          - Name: REACT_APP_BUCKET_NAME
            Value: ${env:BUCKET_NAME}
  Outputs:
    AppId:
      Description: Amplify App ID
      Value: !GetAtt AmplifyApp.AppId

