service: storage

provider:
  name: aws
  profile: ${opt:aws-profile}
  region: ${opt:region}
  deploymentBucket:
    name: ${env:APP_NAME}-deployment-bucket
  stackName: ${env:APP_NAME}-storage

resources:
  Resources:
    StorageBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: ${env:APP_NAME}-storage-bucket
    StorageBucketPolicy:
      Type: 'AWS::S3::BucketPolicy'
      DependsOn: StorageBucket
      Properties:
        Bucket: ${env:APP_NAME}-storage-bucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: AllowWriteUser
            Action:
            - s3:PutObject
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - StorageBucket
                - Arn
            Principal:
              AWS:
              - ${env:AUTH_ROLE_ARN}
  Outputs:
    BucketName: ${env:APP_NAME}-storage-bucket
                
